### PR TITLE
CLI --language option

### PR DESCRIPTION
**Pull request by danascheider**
This PR reintroduces the changes made in @esdoppio's closed PR #975. 
## Summary

This is a feature file for a new CLI flag, `--language`, enriching the API for users to select i18n options using the command line tool.
## Details

The feature describes a proposed command line flag `-L, --language`, that would enable a user to select a language using the command line tool without having to add a language header to each feature file. Using this option, features would be run in the specified language, raising an error if the language specified on the command line is not the one in use in the feature file. The command line option would be overridden by a language header if one is present.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Checklist:

- [x] I've added tests for my code
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danascheider** [comment]
@mattwynne @tooky @brasmusson How do you think would be the best way to implement this? I'm having a little bit of trouble keeping things modular since the language is determined in the Gherkin parser and this option would need to get in there from the CLI. Any ideas?

**Comment by brasmusson** [comment]
@danascheider One way to pass the default language to the parser is to add it pass it to the [`Document` object](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/runtime.rb#L115), then a `TokenMatcher` for the language can be created ([like this](https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/gherkin/steps_parser.rb#L16)), and passed to the [`parse` method](https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/gherkin/parser.rb#L26).

**Comment by danascheider** [comment]
Thanks @brasmusson!

**Comment by danascheider** [comment]
@brasmusson @mattwynne This PR is failing Travis because the changes to core, which I made a PR for as well. How do we deal with this issue?

**Comment by mattwynne** [comment]
@danascheider I think the changes to the core are all merge in now, no?

**Comment by mattwynne** [comment]
@danascheider try rebasing master, I have a feeling this JRuby failure has been fixed.

**Comment by danascheider** [comment]
@mattwynne Will do - sorry - just came back from 3 weeks of vacation and I've got a ton of stuff to catch up on.

**Comment by mattwynne** [comment]
It's a tough life

**Comment by danascheider** [comment]
FML :wink:

**Comment by olleolleolle** [comment]
@mattwynne A quick note, the `spec/cucumber/cli/options_spec.rb` file has Git merge conflict markers committed to this PR, perhaps that's an artifact of a rebase?

**Pull request closed without merging**
