### PR TITLE
History.md Update

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Summary

History.md update.

## Details

* 6 PRs
* They're in numerical order too!

## Motivation and Context

We need to keep track of what's changed!

## How Has This Been Tested?

Code change is only to a .md file, but `bundle exec rake` is 👍 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update.

### CODE REVIEW

**Comment by jaysonesmith** [comment]
Waiting on Travis to finish before merging though there's no change to code. :p

**Comment by brasmusson** [comment]
@mattwynne Don't you also think that a explicit note at the top of the History.md about the intended ordering of entries, both would help the readers, and us contributors?

I elaborated my personal preference in [the_greenhouse slack forum](https://cucumberbdd.slack.com/archives/C60FTHJ22/p1502818938000021?thread_ts=1502740052.715086&cid=C60FTHJ22).

@jaysonesmith I prefer a "latest change first" ordering, but I don't want to criticise you, it the support for contributors that is not as good as it should be.

**Comment by mattwynne** [comment]
> @mattwynne Don't you also think that a explicit note at the top of the History.md about the intended ordering of entries, both would help the readers, and us contributors?

Yes, though I'd prefer to advise people to use the script, which should do that consistently now.

**Comment by jaysonesmith** [comment]
@brasmusson That's easy enough to change moving forward! :+1:

**Pull request merged**
