### PR TITLE
Omit Appveyor runs whilst failures are investigated

### PR DESCRIPTION
**Pull request by luke-hill**
## Summary

Disable Appveyor from running whilst it has large amounts of failures

## Types of changes

- [ ] Refactor (code change that does not change external functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Related Links:
https://github.com/cucumber/cucumber-ruby/issues/916 - Allow Windows Users to Develop
https://github.com/cucumber/cucumber-ruby/pull/1116 - @enkessler adding AppVeyor / Updating Travis (June 2017)
https://github.com/cucumber/cucumber-ruby/issues/1215 - Outstanding Issue to fix Windows builds @jaysonesmith / @bv have done some investigation on this, I've done a little bit myself.

### CODE REVIEW

**Comment by enkessler** [comment]
Reacting to failing tests by turning them off sounds horrible.

**Comment by luke-hill** [comment]
I think it was more of a they've been failing for 6-12months and no-one has been able to / had time to fix them.

We can either leave them on; and spend 3-4* as long diagnosing potential PR's to merge,
Or we can fix the issues,
Or we can turn them off.

Of those 3, I predict the top option is the worst, the middle option is the best - but hasn't happened for over a year, and the bottom is a tolerable evil. If the choice was only between the top and the bottom, I would pick the top one.

Obviously I've left this open as a bit of a conversation starter / discussion topic, because as a tester I don't like ignoring tests, but a few people haven't made much progress with it.

**Comment by enkessler** [comment]
> no-one has been able to / had time to fix them.

If no one's had the time, then I posit they don't have the time to be making any other changes either. If no one has been able to fix them, then I posit that the failures should be even more concerning because it suggests that Cucumber lacks Windows support.

**Comment by enkessler** [comment]
I am aware, yes, that I am the holder of unpopular opinions.

**Comment by luke-hill** [comment]
I dunno, I guess just from some of the stuff the people at Cukenfest spoke about, one was a barrier to contribution. I'm aware that we should be fixing stuff up before pushing new stuff up. But most of the stuff people are working on now is either the migration to Cucumber4 (So using Protobuf e.t.c. and quite complex), generic tidying / docs work, or fixing bugs.

I've primarily been focusing on the latter, fixing up what I can with my knowledge / experience. I've also looked into some of the older long standing issues, to try make everything a bit more up to date (I've also mirrored this on cucumber-rails and aruba).

I've nothing against leaving everything as the status-quo. But I personally don't think it's good, because then we're just letting stuff keep being marked as red, and then we have to (Or at least I do), dive in to make sure no "additional" stuff is broken. Furthermore you need to keep a mental note (Or mental link), to which failures are "known about" because it's not very obvious from the windows failures, as the appveyor logs are insanely long, and cap off at 2000 lines. More than I'd like to read to find out, to find out the same stuff is broken as before.

I've got more thoughts / feelings but I'll wait to see what others say first.

**Comment by jaysonesmith** [comment]
@enkessler While I too think that disabling tests because they're failing is a poor thing to do, I also understand @luke-hill's take on things and I can agree with points from both of you. We've got some tests that are outright skipped on Windows as well and those predate my involvement on the project, so we've been lacking for some time anyhow.

Unfortunately, there are only a few of us contributors, perhaps really only you and I @enkessler, who have windows machines to develop on, which limits the ability for things to be worked on, too. It's a tough spot for the project to be in for sure. We also don't have folks blowing up our issues page about things on Windows being broken, so we're at least _somewhat_ okay right now.

I support disabling things **for now** and perhaps when I'm not tied up freelancing, I can try to get the Windows stuff working again before anything else. You too, @enkessler, are also of course welcome to take up the mantle and get things green again. :)

**Comment by enkessler** [comment]
Inability to build the project locally is a heck of a hurdle for entry. It's always been the largest hurdle to entry for me, anyway. That's why I put together the Windows CI in the first place. Even at that time, several tests were disabled on Windows because there is only so much time and effort on my part to go around. But that was a stable starting point. All that had to happen was to not degrade from there. Asking new contributors to clean up years of legacy code is a big ask. Asking them to simply not make the existing code worse (i.e breaking the build) is a small ask.

> Unfortunately, there are only a few of us contributors, perhaps really only you and I @enkessler, who have windows machines to develop on, which limits the ability for things to be worked on, too. It's a tough spot for the project to be in for sure. We also don't have folks blowing up our issues page about things on Windows being broken, so we're at least somewhat okay right now.

If there is time and money for an organization to host international conferences and workshops to encourage the use of their product to enterprise level companies, then there really should be the time and money to buy a copy of Windows and keep the build green so those same users aren't relying on "well, it's hasn't broken (that we know of)  _yet_".

**Comment by luke-hill** [comment]
That's a fair point. I don't know of the situation wrt finances e.t.c. All I would say is I'm looking at the situation currently. I know in the past we had a good situation with windows tests, but currently they're causing delays (for me, personally).

**Comment by luke-hill** [comment]
Given this change actually doesn't disable appveyor I feel as though something else needs to be done.

I'll ask around in committers but does anyone know the switch I didn't press?

**Comment by luke-hill** [comment]
@aslakhellesoy is this something that the guys at SmartBear could look into perhaps? It would possibly make this PR redundant

I'm also convinced it's not done what I had intended as the appveyor builds are still running.

**Comment by mattwynne** [comment]
Having a green build on master is non-negotiable.

I am interested to understand how we got here. Have we been merging in PRs that didn't pass all our checks? Have people been pushing to master from non-Windows boxes and not noticing that they broke the build?

**Comment by luke-hill** [comment]
June/July 2017 everything was green.

September/October 2018 the windows builds were red (As were JRuby 2.1, 2.2 and 2.3 builds)

Since March 2019 we have removed 2.1 and 2.2
I fixed up some of the 2.3 issues, this now builds fine.
JRuby has been marked as allowed to fail

**NB: This branch isn't up to date**

**Comment by luke-hill** [comment]
Whats the plan of attack here @mattwynne >?

**Comment by luke-hill** [comment]
Closing in favour of other work being undertaken by @vincent-psarga

**Pull request closed without merging**
