### PR TITLE
Fix spacing inside array percent literals and block braces

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Details
- Layout/SpaceInsideArrayPercentLiteral
- Layout/SpaceInsideBlockBraces
- Fixed with auto and tested

## Motivation and Context

Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021)!

## How Has This Been Tested?

`bundle exec rake` :+1:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Rubocop style fixes

### CODE REVIEW

**Comment by jaysonesmith** [comment]
@olleolleolle Thanks! I wonder if I based a branch off another instead of switching to master first? Oh well, it won't be impossible to fix. :p

**Comment by xtrasimplicity** [comment]
Reopening, as this is still useful.

**Comment by jaysonesmith** [comment]
Keeping open

**Comment by jaysonesmith** [comment]
@danascheider All set. I can merge it myself when things are all done, too. Either way is fine. :)

**Pull request merged**
