### PR TITLE
Simplify output of '--i18n LANG'

### PR DESCRIPTION
**Pull request by esdoppio**

### CODE REVIEW

**Comment by danascheider** [comment]
@esdoppio Is there a reason you closed this PR without it being merged?

**Comment by esdoppio** [comment]
@danascheider I don't know. My branch conflicts with the master now; now I have to resolve the conflicts so it can be merged, but I don't want to. And no one seems to care about the changes.

Anyway, you can always reopen it if you want to :metal:

**Comment by mattwynne** [comment]
I dropped the ball on these. I very much appreciate your contribution @esdoppio, I like these changes, and we'll definitely get them merged ASAP. I'm really sorry we gave you the impression we didn't care.

**Comment by mattwynne** [comment]
Also, I don't know why the `for review` tag got removed 7 hours ago! I didn't do that. 😕

**Comment by mattwynne** [comment]
> Anyway, you can always reopen it if you want to

Reopen button is grey for me: "The repository that submitted this request has been deleted" 😞

**Comment by danascheider** [comment]
I can go ahead and create new PRs with the changes.

**Comment by brasmusson** [comment]
@mattwynne I would say that the `for review` tag was removed automatically when the PR was closed (how can I closed PR be "for review"?). Probably a GitHub rule (or are you having a Waffle board connected to this repo?).

**Pull request closed without merging**
