### PR TITLE
Remove the legacy_api

### LINKED ISSUE #839: Re-write formatters against new API
For 3.0 the https://github.com/cucumber/cucumber/blob/master/lib/cucumber/formatter/legacy_api/adapter.rb should be removed, and all formatters that ship with Cucumber should go through the new, test-case based API.

Altogether there are:
- ~~progress (#859)~~
- ~~pretty~~ (#1305)
- ~~html~~ (#1306)
- ~~json~~ (#851)
- ~~json_pretty~~ (is the same as json)
- ~~junit (#855)~~
- ~~stepdefs (#859)~~
- ~~usage (#859)~~
- ~~debug~~ can be removed - only for help writing old-API formatters
- ~~rerun~~ done in (83a0c75cbaa3ded4a5c2f596cbfdcd257fa73cb0)

I think the progress formatter is the place to start, as there's a lot of shared code in all the console formatters. If you want to tackle one, please create a ticket and reference this ticket.

### PR DESCRIPTION
**Pull request by brasmusson**
## Summary

Remove the legacy_api.

## Details

As soon as all formatter have been re-written to use the new formatter api (see #839), the legacy_api should be removed.

Closes #839.

## Motivation and Context

The legacy_api was only intended as a short term fix in v2.0.0.

## Types of changes

- [ ] Refactor (code change that does not change external functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mattwynne** [comment]
\o/

@brasmusson how about we set the master branch to target v4.0.0 and try and just rip out all this old code, including the pretty/html formatters, then rebuild from there?

My only concern is that there may be quite a few scenarios that depend on the pretty formatter, though I could be wrong.

**Comment by brasmusson** [comment]
Around half of the scenarios fail when the `pretty` and `html` formatters do not work. A bit less than half if the default formatter is changed to `progress`, otherwise more than half (137 out of 210) of the scenarios fails. So yes, a lot of our feature files depends on the `pretty` formatter.

**Comment by olleolleolle** [comment]
I’m interested in this being open.

**Comment by mattwynne** [comment]
💖 hooray!

**Pull request merged**
