### PR TITLE
Fix Style/AndOr

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Summary

Fixing Style/AndOr violations

## Details

* Offense count: 11 according to yml

## Motivation and Context

Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021)!

## How Has This Been Tested?

`bundle exec rake` :+1:

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by jaysonesmith** [comment]
Thanks again, @olleolleolle ! I've done some grouping, but anything that has a handful of changes it'd make sense to keep them separate. (Especially since that's part of the request in the root issue!)

**Comment by mattwynne** [comment]
@olleolleolle feel free to merge these if you like 'em :)

(please remember to [update History.md](https://github.com/cucumber/cucumber-ruby/blob/master/scripts/update-history) when you do)

**Comment by mattwynne** [comment]
Or indeed merge it yourself @jaysonesmith 👍

**Comment by jaysonesmith** [comment]
History.md has been updated. PR coming soon. (Including my other PRs)

**Pull request merged**
