### PR TITLE
Example scenario for misleading result data in Around hook

### PR DESCRIPTION
**Pull request by borsothy**
Companion PR for issue #951.

### CODE REVIEW

**Comment by mattwynne** [comment]
Thanks, this will make it a lot easier for us to get this working.

**Comment by danascheider** [comment]
@gergelyborsothy Can you tag this as `@wip`? That way we can merge this without breaking Travis while we investigate the issue further.

**Comment by gergelyborsothy** [comment]
@danascheider I can't apply labels 😦

**Comment by danascheider** [comment]
Oh, @gergelyborsothy, I meant tag the feature as @wip, not the issue:
```gherkin
@wip
Feature: Whatever the feature is
  Scenario: Whatever the scenario is
  ...
```

**Comment by danascheider** [comment]
Actually, @gergelyborsothy, never mind - I just saw a new PR changing that so `@wip` features will break the builds after all. So what we'll do with this is leave it open until the right code is added to make the feature pass.

**Pull request closed without merging**
