### PR TITLE
Reintroduce changes from PR #978

### PR DESCRIPTION
**Pull request by danascheider**
This PR reintroduces @esdoppio's changes from #978, which was closed without being merged.

### CODE REVIEW

**Comment by mattwynne** [comment]
@danascheider this needed rebasing and also had a failing test. I think I've fixed both but can you review for me and merge if you think it's OK?

**Comment by mattwynne** [comment]
Argh it's not right is it. Something went wrong in the merging of the `options.rb` file.

**Comment by mattwynne** [comment]
@danascheider I'm sorry I've made a mess of this! I've run out of time to fix it. Can you take a look?

**Comment by mattwynne** [comment]
@danascheider it would be nice to get this into the 3.0.0 release. Will you have a chance to look at it do you think?

**Comment by danascheider** [comment]
I can look at it again after work today.

**Pull request closed without merging**
