### PR TITLE
AfterAll hooks

### PR DESCRIPTION
**Pull request by abezzub**
As suggested in https://github.com/cucumber/cucumber/issues/853 this PR first adds a failing `.feature` file. I will try to look at Cucumber code and make tests pass, but let me know if you have any suggestions about tests or next steps that I should take.

### CODE REVIEW

**Comment by mattwynne** [comment]
This spec looks great. Have you had a look at the code with a view to doing the implementation?

**Comment by mattwynne** [comment]
Need any help @abezzub?

**Comment by mattwynne** [comment]
Question for you @abezzub: What should happen if an exception occurs in the `AfterAll` hook?

**Comment by abezzub** [comment]
Sorry, I got sidetracked on a different project. 

I would expect cucumber to return an error exit code in this case.

**Comment by mattwynne** [comment]
Thanks @abezzub. Do you think we should present the exception in the output too? Would you like to sketch out a scenario for this?

**Comment by wjlroe** [comment]
@mattwynne we have been bitten by this at work, I can pick this up and continue the work if that's the right thing to do?

**Comment by mattwynne** [comment]
Thanks @wjlroe that would be very much appreciated. Remember we do need to consider the exit codes too, and add that to the acceptance test.

**Comment by mattwynne** [comment]
Closing in favour of #1011

**Pull request closed without merging**
