### PR TITLE
Fix Style/AlignParameters

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Details

- Rubocop prefers parameters of a method call to be tabbed to the same depth if they span multiple lines.

## Motivation and Context

Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021)!

## How Has This Been Tested?

`bundle exec rake` :+1:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Rubocop style fixes

### CODE REVIEW

**Comment by luke-hill** [comment]
With the squiggly's (I assume they're heredocs). I actually think aligning them with the speech above is slightly wrong. Because the part of "context" they refer to is the capital STEPS or FEATURE below.

Would be interested to know what happens on the interpreter if you add a newline above them, whether then they pass?

**Comment by jaysonesmith** [comment]
Will work to fix conflicts today if I can!

**Comment by jaysonesmith** [comment]
@luke-hill Which herdoc references are you talking about? Perhaps that was meant for another PR?

**Comment by jaysonesmith** [comment]
Tyvm @olleolleolle !

**Pull request merged**
