### PR TITLE
Add the description of a new cli option --language

### PR DESCRIPTION
**Pull request by esdoppio**
@mattwynne

### CODE REVIEW

**Comment by mattwynne** [comment]
👍 

That is perfect @esdoppio thank you!

Are you interested in having a crack at implementing it? We can give you as much guidance as you need.

**Comment by esdoppio** [comment]
@mattwynne sure, yes. Cucumber is awesome, just so glad I can participate : )

**Comment by mattwynne** [comment]
What happened with this one @esdoppio? Your spec was awesome! Did you lose interest in making the implementation? Or was it because we dropped the ball with your refactoring commits?

Feel free to hassle me in https://gitter.im/cucumber/cucumber-ruby if I'm being unresponsive. I have a lot on my plate but I care greatly about helping new contributors, and I'm always glad to be asked for help.

**Comment by danascheider** [comment]
@mattwynne I just opened #989, which reintroduces these changes. @esdoppio If you'd still like to take a crack at implementing this, I would have time to help with it and make sure it gets the attention it needs. Otherwise, I will put it together shortly.

**Comment by esdoppio** [comment]
Talked to Matt about opening new PRs. Now that you've done it already, it's all yours, do what u like. I was planning to implement it after the other PR is merged, coz some of the methods could be reused after refactoring. It feels funny, no one had showed any interests until I closed them, now someone is so eager to implement it lol.

**Comment by danascheider** [comment]
I think things tend to fall off our radar as we have a huge number of issues to attend to, and we all got notifications when you closed the PRs. We're really sorry about that, @esdoppio! (And speaking for myself, I've been known to forget about my own PRs, so nothing personal!)

**Comment by esdoppio** [comment]
None taken, "sorry" is a strong word here lol. I closed it mainly coz I thought the changes were not needed, the PR was just there occupying the space, and the changes were stale. Honestly, when I closed the PRs, I didn't expect anyone to notice or say anything; it feels a bit like a drama now. Let's not linger on this any more :metal:

**Pull request closed without merging**
