### PR TITLE
Adding Test Step in AfterStep feature file.

### PR DESCRIPTION
**Pull request by t-morgan**
Working on Add step to AfterStep #450 

Do you think the argument list should be consistent with how formatters work or will it potentially cause problems moving the current argument out of its position as first argument?

### CODE REVIEW

**Comment by brasmusson** [comment]
Isn't not having `scenario` as first argument to the AfterStep hooks, such a breaking change that only can be introduced in a major version upgrade?

If the intention is to add both `step` and `result` as arguments to AfterStep hooks, I see it as two separate changes, from:
```
Before do | scenario |
After do | scenario |
AfterStep do | scenario |
```
to:
```
Before do | scenario |
After do | scenario |
AfterStep do | scenario, step |
```
And another change to.
```
Before do | scenario |
After do | scenario, scenario_result |
AfterStep do | scenario, step, step_result |
```

**Comment by t-morgan** [comment]
I could be wrong, but it seems to me that since upgrading to Cucumber 2 the only argument I an receiving from the AfterStep hook is a Cucumber::Core::Test::Result of whatever status the step invocation was.

**Comment by brasmusson** [comment]
Hm, based on #450 I thought that the AfterStep hooks in Cucumber v2 received a Cucumber::RunningTestCase, as the Before and After hooks do.

**Comment by t-morgan** [comment]
It was definitely a scenario object in Cucumber 1.x when the issue was first reported (and it was pretty simple to get the step through that scenario at the time).

In Cucumber 2.x, I am only finding a result in the AfterStep block (Before and After still receive the scenario as normal). 

I know I can add the test_step when the hook action is created in the after_step_hooks method of Cucumber::Runtime::StepHooks in lib/cucumber/runtime/step_hooks.rb and my test will pass... I'm just not sure if that is the right/best place to do it.

**Comment by t-morgan** [comment]
I went ahead and implemented my change to fix the AfterStep hook functionality. If there are any changes that should be made, please let me know.

I had to flatten an array in lib/cucumber/rb_support/rb_hook.rb because the argument passed into the AfterStep hook was being wrapped in an Array for some reason.

**Comment by mattwynne** [comment]
Thanks sharing your fix @t-morgan.

**Comment by mattwynne** [comment]
Could you rename the feature (and reword the description) to just be a general feature for AfterStep hooks? It should live here: https://github.com/cucumber/cucumber-ruby/tree/master/features/docs/writing_support_code

**Comment by t-morgan** [comment]
Hey @mattwynne, I cleaned up the feature file and moved it as you requested. I think it might be a good idea to also include another scenario showing AfterSteps do run for background steps (apparently this was not always the case).

**Comment by maxmeyer** [comment]
@t-morgan What would be a "background step"? Some command running in the background?

**Comment by t-morgan** [comment]
@maxmeyer, no it is just a step defined under 'Background:' for the feature.

**Comment by maxmeyer** [comment]
Ah. Ok. :-)

**Comment by gergelyborsothy** [comment]
Are you planning to merge this to master? We're planning to measure the time it takes a step to complete, and this modification would be extremely useful.

**Comment by chewi** [comment]
Please merge it, AfterStep is quite useless in its current form.

**Comment by chewi** [comment]
Is there a nicer way to get the index of the step other than this?

```ruby
step.source[-2].children.index(step.source.last)
```

**Comment by mattwynne** [comment]
Thanks @t-morgan!

**Comment by mattwynne** [comment]
As part of our new policy I've invited you to become a committer to this repo @t-morgan. I liked how you found your way around the code and tested your change. I hope we'll get more contributions from you in future!

**Comment by djwgit** [comment]
@mattwynne @t-morgan 
with cucumber-ruby gem 2.3.3,  I got nil class for the test_step... is this expected? according to the after_step_hooks.feature, it should be the step, right?  not sure if I missed something... thanks

```
AfterStep do |result, test_step|
  print result.class
  print "\n-------\n"
  print test_step.class
end
```
I got this
```
Cucumber::Core::Test::Result::Passed
-------
NilClass
```

**Pull request merged**
