### PR TITLE
Add rubocop gem and config

### PR DESCRIPTION
**Pull request by nodo**
* add `rubocop` gem to the development dependencies
* add default configuration (auto-generated) to keep track of the offences

Please, comment below if you want to add specific style preferences such as line length, method length, etc. After, that we can gradually fix the offences.

Resolves https://github.com/cucumber/cucumber-ruby/issues/1014

### CODE REVIEW

**Comment by mathieujobin** [comment]
it does not look like rubocop runs on travis, I think it should, and also fail the build if there are regressions.
this would mean the rubocop_todo file will need to be updated quite often for PR to be merged.
the alternative, is a dormant rubocop_todo file that will be updated on a voluntary basis.

**Comment by nodo** [comment]
@mathieujobin I agree I think we should add rubocop to Travis eventually. I didn't add it yet because I think we should agree on some style guidelines. Moreover, there are still some offences not captured by `.rubocop_todo.yml` and therefore the build will fail at the moment.

My plan is the following: 
1. Get this PR merged with a sensible configuration for `rubocop`
2. Fix the remaining offences and add it to Travis
3. Open a issue labelled "Easy" to fix the remaining offences and gradually empty the `.rubocop_todo.yml`.

What do you think?

**Comment by brasmusson** [comment]
@nodo How do you mean that #1014 is related? If you mean the #1014 can be closed when this PR is merged, then that should be phrased in the description with a [keyword for closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) (for instance "closes #1014"), then Github will do that automatically.

**Comment by nodo** [comment]
Thanks for the hint @brasmusson  I didn't know that. I have changed the commit message and title of the PR accordingly.

**Comment by brasmusson** [comment]
@nodo Unfortunately you edited the PR title, which actually is the least useful place to refer to other issues. In a PR title a issue reference will neither be a clickable link nor will it help with the closing of issues automatically. In the PR description (the top comment, which in the RP end with "Related issues: ...") issue references (with the closing keyword) will be both clickable links and will help the the closing of issues automatically (and in RP comments issue references will be clikcable links, but will never help with the closing of issues).

**Comment by nodo** [comment]
@brasmusson Thanks for the clarification. I have reverted the title change. However, I did change also the commit message which AFAIU will close automatically the issue. Am I wrong?

**Comment by mattwynne** [comment]
Great idea! @nodo could you add something to contributing.md that points people to the TODO file? There's bound to be loads of low-hanging fruit in there for beginners to get stuck in to.

**Comment by mattwynne** [comment]
And yes, the issue was automatically closed :0

**Pull request merged**
