### PR TITLE
Upgrade gherkin and cucumber expressions

### PR DESCRIPTION
**Pull request by aslakhellesoy**
Upgrade to latest versions

### CODE REVIEW

**Comment by olleolleolle** [comment]
Curious about why the jruby build failed "to SSH".

**Comment by aslakhellesoy** [comment]
No idea - let's see if your retrigger fixes it

**Comment by luke-hill** [comment]
Yeh was about to say, on any CI environment (Travis/Circle/Jenkins), I've had sporadic failures (probably < 0.1%), for weird build instructions or something that's come through in the wrong order. Just close/reopen and give it a kick.

**Comment by xtrasimplicity** [comment]
Woo! Assuming this passes, can we rebase #1296 and kick off a new release?

**Comment by aslakhellesoy** [comment]
@xtrasimplicity yes I think a new release is overdue! Do you want to handle that?

I prefer merging over rebasing :-) https://medium.com/@fredrikmorken/why-you-should-stop-using-git-rebase-5552bee4fed1

**Comment by xtrasimplicity** [comment]
@aslakhellesoy Awesome! Yep, I can do that.

Thanks for the heads up re: merging, and for the link - I'll take a read and will make sure I merge. :)

**Comment by xtrasimplicity** [comment]
With jruby, we're using the alpine image which may not include the git client (given alpine is pretty lightweight), maybe we should move to a circle I-specific JRuby image? 

I.e. `circleci/jruby:9.1.16.0-jdk` rather than ` jruby:jruby:9.1.16.0-jdk-alpine`?

**Comment by xtrasimplicity** [comment]
Switched the JRuby image in CircleCI config from the Alpine image to the CircleCI one, which has fixed the CI issues. Merged! :+1:

**Pull request merged**
