### PR TITLE
Rake task fix_cr_lf: exclude iso-8859-1 files

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR changes the `fix_cr_lf` Rake task: it now fixes CRLF **on the right files**.

The previous exclusion rules were for files with `dos` in the filename – these files are no longer a part of the codebase.

Also: tell Git how to clone files using the [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/) documentation that GitHub wrote.

### CODE REVIEW

**Comment by enkessler** [comment]
The changes themselves look fine. What's been happening with that `iso-8859-1` file before this fix?

**Comment by olleolleolle** [comment]
@enkessler My guess is "task has not been run" so, nothing. 

In order to be more explicit, we could exclude specifically the TWO other-encoded files.

 Perhaps give them their own FileList to prep for an impl which actually CRLF-fixes those two files as well. And, I _think_ exclude can be done using the filelist objects with subtraction.

**Comment by enkessler** [comment]
Out of curiosity, is there a setting that we can simply adjust so that all files get saved with LF instead of CRLF?

**Comment by olleolleolle** [comment]
@enkessler There is. A gitattributes dotfile can assist with that with an auto-rule matching file patterns. 

Life-learning: not all files like being transformed. So, some file patterns to be transformed may be called for. 

Maintaining the `.gitattributes` file is less troublesome than having CRLF issues, I guess.

**Comment by olleolleolle** [comment]
@enkessler I now see that GitHub's Help pages have documented this to a high degree: https://help.github.com/articles/dealing-with-line-endings/

**Comment by olleolleolle** [comment]
Eh, @aslakhellesoy, did you author the original Rake task?

Would you say that the above  Git attributes solution makes the Rake task superfluous?

**Pull request merged**
