### PR TITLE
Refactor cli options

### PR DESCRIPTION
**Pull request by danascheider**
## Summary

This PR refactors the `#parse!` method for the `Cucumber::Cli::Options` class.

## Details

I extracted descriptions and option handlers to new private methods and turned the `opts.on` blocks into single lines.

## Motivation and Context

I noticed that Code Climate had rated this class F, and when I looked at the code, I could see why. I think the new way is more readable.

## How Has This Been Tested?

I tested the changes using the existing test suite to check for regressions. Since I didn't add or remove functionality, new tests were not required.

### CODE REVIEW

**Comment by mattwynne** [comment]
I love the extracted helper methods. I wonder if, to keep the abstraction level consistent in the `opts.on` blocks, it would be better always use a helper method, even when it's only a one-liner. WDYT?

**Comment by mattwynne** [comment]
Maybe two methods: `set_option` and `unset_option` would do.

e.g. `set_option :strict`

**Comment by danascheider** [comment]
I love that idea.

**Comment by danascheider** [comment]
@mattwynne Was there anything else you thought should be changed here?

**Comment by mattwynne** [comment]
No, looks bloody marvellous to me @danascheider! I'm really happy to see you cleaning the code up like this.

**Comment by mattwynne** [comment]
I know it feels a bit weird merging your own PR so I did it 😄 

I don't personally think this needs to go into `History.md` as it doesn't change any externally-visible behaviour but I may be biased by the fact that I'm doing this via the GitHub UI, it's late and I'm feeling a bit lazy. @brasmusson you tend to have good opinions about these things - WDYT?

**Comment by danascheider** [comment]
Thanks @mattwynne!

**Pull request merged**
