### PR TITLE
Update cucumber-html-reporter dependency to 15.0

### PR DESCRIPTION
**Pull request by srbarrios**
# Description

This PR updates the `cucumber-html-reporter` to the latest version.
The current version 13.0 produce a wrong HTML format, showing every attachment/log call in the same row, when we actually expect a new line after each attachment/log.

**Depends on:** https://github.com/cucumber/cucumber-ruby-core/pull/220

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Update of dependency

# Checklist:

Your PR is ready for review once the following checklist is
complete. You can also add some checks if you want to.

- [ ] Tests have been added for any changes to behaviour of the code
- [ ] New and existing tests are passing locally and on CI
- [ ] `bundle exec rubocop` reports no offenses
- [ ] RDoc comments have been updated
- [ ] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Thanks @srbarrios 

It is planned to release cucumber-ruby "soon". I keep your PR in mind to make sure the html-formatter is dumped to the latest version in the process

**Comment by srbarrios** [comment]
These changes will not work if we don't first bump up cucumber-core dependency so it use a newer version of cucumber-messages.
I create this Pr for that purpose https://github.com/cucumber/cucumber-ruby-core/pull/220

Also, I guess this PR is missing a change of version of cucumber-core, so it use a newer one with the problem solved.
Once we have a new version of cucumber-core I can make the change here.

**Comment by aurelien-reeves** [comment]
Actually we even need to release new versions of gherkin and messages first 😅
Cf. https://github.com/cucumber/cucumber-ruby-core/pull/220#issuecomment-875483578

**Comment by srbarrios** [comment]
Closing this draft in favour of a major change that @aurelien-reeves has planned.

**Pull request closed without merging**
