### PR TITLE
Fix Style/AlignArray

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Summary

Partially Fixing Metrics/AlignArray

## Details

* All offending directories except 'spec/cucumber/formatter/legacy_api/adapter_spec.rb' which has 1106 offenses

## Motivation and Context

Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021)!

## How Has This Been Tested?

`bundle exec rake` :+1:

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by jaysonesmith** [comment]
Before I get started on (the adapter_spec file)[https://github.com/cucumber/cucumber-ruby/blob/master/spec/cucumber/formatter/legacy_api/adapter_spec.rb#L114-L151], it seems like the indentation here was done for visibility, but not all arrays are done this way?

Should I still fix this?

**Comment by mattwynne** [comment]
Yes the indentation on the adapter spec is done for visibility. We intend to remove that code before too long anyway, so I think we could put inline exceptions for those and leave them as they are.

**Comment by jaysonesmith** [comment]
That makes sense and is doable. Thanks!

**Comment by jaysonesmith** [comment]
Finished the inline exception work. This cop should be all set now!

**Comment by jaysonesmith** [comment]
History.md has been updated. PR coming soon. (Including my other PRs)

**Pull request merged**
