### PR TITLE
Deprecate safe_level of ERB.new in Ruby 2.6

### PR DESCRIPTION
**Pull request by koic**
## Summary

The interface of `ERB.new` will change from Ruby 2.6.

> Add :trim_mode and :eoutvar keyword arguments to ERB.new.
> Now non-keyword arguments other than first one are softly deprecated
> and will be removed when Ruby 2.5 becomes EOL. [Feature #14256]

https://github.com/ruby/ruby/blob/2311087/NEWS#stdlib-updates-outstanding-ones-only

## Details

This PR uses `ERB.instance_method(:initialize).parameters.assoc(:key)` to switch `ERB.new` interface. Because Cucumber multiple Ruby versions, it need to use the appropriate interface. This approach is built into Ruby.
https://github.com/ruby/ruby/commit/3406c5d

### CODE REVIEW

**Comment by danascheider** [comment]
@koic Thanks for the PR! I just had one quick question I was wondering if you could answer before I merge it.

**Comment by xtrasimplicity** [comment]
This looks good, but is there a real benefit to using `ERB.instance_method(:initialize).parameters.assoc(:key)` rather than just `RUBY_VERSION >= '2.6'`? I understand it's in the official ruby repo, but I'm not sure the complexity is otherwise justified?

**Comment by koic** [comment]
AFAIK, comparison using Ruby version number seems to tend to be less favored. If Ruby version is easier to understand as Cucumber, I will replace `ERB.instance_method(:initialize).parameters.assoc(:key)` with `RUBY_VERSION >= '2.6'`. So, of course there is no problem with this.

**Comment by xtrasimplicity** [comment]
Thanks, @koic. In the interest of keeping things simple, and assuming there's no disadvantages to doing so, I think it would be best if we use the `RUBY_VERSION` comparison method. Thanks once again for your work on this.

@danascheider, do you still have questions regarding this PR?

**Comment by koic** [comment]
I get it! I updated this PR using `RUBY_VERSION`. Would you please review again?

**Comment by xtrasimplicity** [comment]
I've merged the `master` branch into this, and have added an (optional) build for Ruby 2.6 into the CircleCI config.

Everything seems OK for Ruby MRI on Linux, but JRuby and Windows (AppVeyor) appear to be having issues. AppVeyor's issues appear to be due to differences between the usage of LF and CRLF on Linux and Windows.

I don't have time to look into this right now, so I'm happy for someone else to take over in the meantime, if you would like. :)

**Comment by aslakhellesoy** [comment]
Hi @koic,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by koic** [comment]
Thank you for inviting me to the Cucumber committers team. I'm very honored!

**Pull request merged**
