### PR TITLE
Add Björn Rasmusson as release manager

### PR DESCRIPTION
**Pull request by brasmusson**
As discussed in https://github.com/cucumber/cucumber-ruby-core/pull/93#issuecomment-119237258.

For the Rubygems email, see the the profile link.

### CODE REVIEW

**Comment by brasmusson** [comment]
@mattwynne Here is the link to the rubygems account I created, and the "Email me" link on the profile page can give you the email address for the account.

**Comment by tooky** [comment]
All done, I think!

**Comment by brasmusson** [comment]
@tooky @mattwynne I got release karma for Cucumber (as far as I can see), thanks, but not for Cucumber-Ruby-Core, should it also be included "in the package"?

**Comment by tooky** [comment]
@brasmusson done! Sorry, missed that :)

**Comment by brasmusson** [comment]
@tooky Great, thanks. I updated the ["grant release karma" instructions in Contributing.md](https://github.com/cucumber/cucumber-ruby/blob/master/CONTRIBUTING.md#gaining-release-karma), for future reminders.

**Pull request merged**
