### PR TITLE
Fix #893 by passing in duration[:duration] which is a number.

### LINKED ISSUE #893: cucumber 2.0.0 -> 2.0.1 breaks fivemat
One of our [builds](https://travis-ci.org/rapid7/metasploit-cache/jobs/71104061) saw the upgrade to cucumber 2.0.1 because we were pinning with `~> 2.0`, assuming semantic versioning, but 2.0.1 gives this error:

```
undefined method `divmod' for #<Cucumber::Formatter::LegacyApi::Ast::Features:0x00000004a3eb30> (NoMethodError)
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/duration.rb:8:in `format_duration'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/console.rb:87:in `print_stats'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/fivemat-1.3.1/lib/fivemat/cucumber.rb:34:in `after_features'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:111:in `after'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:47:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/runner.rb:35:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/filters/quit.rb:17:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/locations_filter.rb:19:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/filter.rb:61:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/compiler.rb:23:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core/gherkin/parser.rb:31:in `done'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:29:in `parse'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-core-1.2.0/lib/cucumber/core.rb:18:in `compile'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/runtime.rb:70:in `run!'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/lib/cucumber/cli/main.rb:38:in `execute!'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/gems/cucumber-2.0.1/bin/cucumber:9:in `<top (required)>'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/bin/cucumber:23:in `load'
/home/travis/build/rapid7/metasploit-cache/vendor/bundle/ruby/2.1.0/bin/cucumber:23:in `<main>'
```

If I downgrade to cucumber 2.0.0 by changing the `~> 2.0` in the `Gemfile` to `2.0.0`, it [works](https://travis-ci.org/rapid7/metasploit-cache/jobs/71110968).

# Summary

| gem           | broke | works |
|---------------|-------|-------|
| cucumber      | 2.0.1 | 2.0.0 |
| cucumber-core | 1.2.0 | 1.1.3 |
| fivemat       | 1.3.1 | 1.3.1 |

### PR DESCRIPTION
**Pull request by envygeeks**
/cc @jekyl/core

### CODE REVIEW

**Comment by envygeeks** [comment]
I don't even have the time to fix all that mess, it seems https://github.com/cucumber/cucumber-ruby/commit/6c346361ca7bb47bd9c6dd52f492b468d6bc4853 and all the tests are broken because none of the tests regression proof themselves and/or weren't updated :cry:

**Comment by parkr** [comment]
Thanks, @envygeeks

**Comment by brasmusson** [comment]
Issue #893 is now fixed, see https://github.com/cucumber/cucumber-ruby/issues/893#issuecomment-121711362.

**Comment by envygeeks** [comment]
Yup, I seen you fixed it so I closed this, thanks!  Is there anyway this can be pushed out today because we have dozens of pull requests failing because of this and I think we'd rather get an update from ya'll than temporarily patch a fix.

**Comment by brasmusson** [comment]
Releasing is out of my hands, so I can't say. If @mattwynne or any other of the release managers can find the time ...

**Comment by mattwynne** [comment]
I've just shipped v2.0.2 from the master branch.

@brasmusson you just need to create a rubygems account and send me the email address and I'll give you release karma.

**Pull request closed without merging**
