### PR TITLE
Update rule feature to test using tags

### PR DESCRIPTION
**Pull request by luke-hill**
Allow Rules to be used in cucumber-ruby

### cucumber-ruby
- Fix the rule test to use a tagged rule

### gherkin
- Fix GherkinQuery to build up the backward looking tag logic when in `Rule` as well as `Feature` (Previously just used feature).

**Additional context**
Needs to be merged AFTER the gherkin fix.

### CODE REVIEW

**Comment by luke-hill** [comment]
This will fail CI currently. Once I've then merged in the fix to gherkin it should then pass.

**Comment by aurelien-reeves** [comment]
Could we have a scenario which tries filtering on the rule's tag?

**Review by aurelien-reeves — APPROVED** [review]

**Comment by luke-hill** [comment]
I think you can see that in the "passing" commit, it did actually pass. I just forgot a line of the tag (Which I copied in the latter commit).

**Comment by luke-hill** [comment]
Note to all: This requires a new version of gherkin-ruby (Slated to be v19.0.4), which in turn will require other things updating first. It is a hard-blocker that those items are released **before** this PR can be rebased and merged.

**Review by aurelien-reeves — APPROVED** [review]

**Pull request merged**
