### PR TITLE
Refactor Circle CI config

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

 - less copy/paste for the commands
 - allow failure for JRuby (same as for cucumber-core)
 - add test with latest Ruby (allow failure here too)

## Checklist:

Not applicable

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
That's the same Rubocop errors I'm getting on the `gherkin-8` branch (that's fixed there), but I don't see them on `master` ...

I there some dark magic somewhere or is it just due to the fat that the build on `master` has not run since almost a month ?

**Comment by luke-hill** [comment]
It could be due to the fact the versions of rubocop were different when they ran.

Rubocop is still in 0.x phase, so they do break it quite a bit.

**Comment by vincent-psarga** [comment]
Okay that explains it :)

**Comment by vincent-psarga** [comment]
The rubocop issues should be fixed by #1369
I think I'll add a nightly build here too (as for the monorepo) to avoid this kind of surprises in the next Rubocop update ;)

**Pull request merged**
