### PR TITLE
Json formatter scenario outline table data in

### PR DESCRIPTION
**Pull request by ransom4real**
## Summary

This PR is meant to provide clarity in JSON Formatter id for Scenario outlines. At the moment this returns just the example row id which is not very descriptive for anyone using the JSON report on Jenkins or any other reporting tool. A comma separated table header and row value seems more appropriate.

## Details

Hence I have written a private helper method to extrapolate the header values, loop through each value using its index and fetch the associated row value using the index of the header as table columns have fixed indexes which means the row values have fixed indexes correlating to the header index. This way i can build a comma separated column=value data to append to the id instead of just an row id which doesn't give any descriptive information

## Motivation and Context

JSON reporting has become the go to formatter for test reporting especially when you have to rerun tests and merge in results from your rerun into the original test report. However this becomes more of an issue with scenario outlines when you try to find out what exact outline example is failing as the current JSON formatter does not give an example data context. This is my motivation for this change. It does not fix any open issues at the moment and it is more of a feature which i reckon will make the JSON formatter used even more.

## How Has This Been Tested?

I have updated all JSON related scenario outline based specs and features. I have also added new tests relating to tables with more than one column to ensure they are mapped correctly and comma separated as required. All tests were executed prior to this PR and they all pass.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've added tests for my code
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by brasmusson** [comment]
Changes to the Json formatter output should be coordinated with the other Cucumber implementations (maybe primarily [Cucumber-JVM](https://github.com/cucumber/cucumber-jvm)), so that tools that process the Json files can be used with more than one Cucumber implementation.

I think that the important trait of the id attribute in the Json file is uniqueness rather than descriptiveness. I would look for descriptiveness in that name attribute and other data attributes. Issue #984, points to a better solution in that respect, I think.

**Comment by ransom4real** [comment]
@brasmusson i did give issue #984 a go but had no luck getting the scenario example data into the title. Also the reason i have fallen back on the id in the JSON is because the name and other attributes are not unique enough especially for Scenario Outlines. I never had issues with normal Scenarios just Outlines. Also it seems #984 is implemented in cucumber-JVM but not really in cucumber-ruby. Are you certain it is possible in cucumber-ruby? Do you reckon this solution will break tools that process JSON reports considering all the spec test and gherking features passed your build process?

**Comment by danascheider** [comment]
@ransom4real Take a look at the conversation on #984 - this is entirely possible but would need to be implemented in [core](https://github.com/cucumber/cucumber-ruby-core).

**Comment by ransom4real** [comment]
@danascheider do you mean #984 or my solution?

**Comment by danascheider** [comment]
984.

**Comment by ransom4real** [comment]
@danascheider i might not get the time to pair on this as this PR was meant to help my work. I will go ahead and close this PR in preference to the #984 solution whenever it is implemented. I will be happy to extend the JSON formatter in my framework and override the examples_table method for my needs. Thanks

**Pull request closed without merging**
