### PR TITLE
Fix incompatible encodings error in Junit formatter

### PR DESCRIPTION
**Pull request by NickAb**
## Summary

Fix  incompatible character encodings error in Junit formatter which occurs if strings with incompatible encodings were written to pipe.

## Details

Replaced array buffer in Interceptor::Pipe with StringIO to prevent  incompatible character encodings error. This also elements need to join array in Junit formatter and reduces exposure of internals of pipe interceptor. Although #buffer method was kept and is backward compatible in case any end user code is using it.

## Motivation and Context

This fixes issues of cucumber failing to generate junit report for test cases that had non UTF strings in different languages logged during test run.

## How Has This Been Tested?

Add test case for junit formatter to write output in case of incompatible strings being logged during test run.

## Types of changes

- [ ] Refactor (code change that does not change external functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by NickAb** [comment]
I am not sure how to make both `is able to strip control chars from cdata` and `is able to handle multiple encoding in pipe` to work at the same time. At the moment newly added tests redefines Junit class which breaks existing test for control characters.

**Comment by brasmusson** [comment]
@NickAb Rebase on the latest commit on master and change `is able to handle multiple encodings in pip` the same way as `is able to strip control chars from cdata` is changed in that commit. Then both should work.

**Comment by NickAb** [comment]
@brasmusson thank you. All done

**Comment by brasmusson** [comment]
Lets add a deprecation warning for [`#buffer`](https://github.com/cucumber/cucumber-ruby/pull/1244/commits/0cc6a781456a27c1578dffc1ff1abeb1524287b9).

**Comment by aslakhellesoy** [comment]
Hi @NickAb,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by brasmusson** [comment]
The fix does not work on JRuby, see https://circleci.com/gh/cucumber/cucumber-ruby/849, and also #1259.

**Pull request merged**
