### PR TITLE
Fix Multiple Cops

### PR DESCRIPTION
**Pull request by jaysonesmith**
## Summary

Fixing multiple, low offense count, cops.

## Details

* Offenses:
  * Style/ClassCheck: 3
  * Style/ClosingParenthesisIndentation: 1
  * Style/ColonMethodCall: 1
  * Style/CommentAnnotation: 1
  * Style/CommentIndentation: 2
  * Style/ConditionalAssignment: 1
  * Style/ConstantName: 1

## Motivation and Context

Working to help solve issue [1021](https://github.com/cucumber/cucumber-ruby/issues/1021)!

## How Has This Been Tested?

`bundle exec rake` :+1:

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by jaysonesmith** [comment]
Thanks @olleolleolle ! I'm still working to get into things/foot in the door/comfortability, so these are working out great! I've got plenty more PRs for linting fixes. LMK if there's anything I need to do on them to get them approved too. Thanks!

**Comment by olleolleolle** [comment]
@jaysonesmith You're doing great on that front: small sets of changes per PR, very small edits, long on Description.

**Comment by jaysonesmith** [comment]
@olleolleolle great, thanks! :D

**Comment by jaysonesmith** [comment]
History.md has been updated. PR coming soon. (Including my other PRs)

**Pull request merged**
