### PR TITLE
Fix windows build

### PR DESCRIPTION
**Pull request by aurelien-reeves**
Install MSYS2 using Chocolatey allow a silent install.
Then, ridk can set-up msys2 properly and the ruby devkit.

**Is your pull request related to a problem? Please describe.**

The circle-ci windows build is broken

**Describe the solution you have implemented**
`ridk` may not be silent when installing `msys2`.
Installing `msys2` using `choco` allows to install it silently, then `ridk install 2 3` can properly set-up the ruby devkit.

### CODE REVIEW

**Comment by luke-hill** [comment]
Given this fixes the windows build. And I know from first hand experience that ridk is often the tricky bit (And we've had a lot of issues in the past here with windows), thankyou very much for looking into this and providing a fix!!!!

I'll approve. Could you write a little changelog message please. Because I know in the past we sometimes have missed "when" the windows build broke specifically. This would help us nail down that in Cucumber 5.x the windows build was good. It'll also probably encourage us to keep it this way :)

Thanks again

**Review by luke-hill — APPROVED** [review]

**Comment by aurelien-reeves** [comment]
Sorry, I've been messy :'(

**Comment by luke-hill** [comment]
Let me know when you want me to look at something.

**Comment by aurelien-reeves** [comment]
Everything is fine now for that PR, it is alright now

**Pull request merged**
