### PR TITLE
Suites

### PR DESCRIPTION
**Pull request by richarda**
Start with a simple example for a suites feature discussed in issue #821.

### CODE REVIEW

**Comment by mattwynne** [comment]
Still got any energy for this @richarda?

**Comment by richarda** [comment]
Sure. I've been out for a while, but I should jump back in. Let me take a look.

**Comment by richarda** [comment]
I am looking at this.  It's taking me a while to catch up.  Would the execution behavior of a suite be implemented similarly to a rerun scenario?

**Comment by mattwynne** [comment]
I think the changes required here are a bit more fundamental @richarda. The code is going to offer some resistance to this change but once it's done we'll have tackled some of the remaining bits of coupling, so you'll need to be brave!

First off, I think we need to model the configuration differently, so that there's configuration for the overall run that won't change (formatters, for example) and then configuration per suite (e.g. tags to filter by).

Then it's a matter of breaking out some of the functionality in `Runtime` into a new `Suite` class that models the execution of a single suite. The `Runtime` would have a list of suites (by default, just one) that it iterates over and executes. The body of `Runtime#run!` and its friends would move into the `Suite` class.

I would start by picking off a single configuration option (like the tags to filter by) and trying to get that to work, then we can iterate and pick off other configuration options that make sense.

Does that help?

**Comment by richarda** [comment]
Yes @mattwynne. That is helpful. That seems like a very good way to get started.

**Comment by richarda** [comment]
Sorry if this is slow progress, but I think I'm starting to get the idea here.
I'm just putting the configuration step inline in `runtime.rb` temporarily but it seems like there should be a method `Cucumber.configure` coming out of this soon.

In what context would this be written?
```
Cucumber.configure do |config|
  config.suite(:domain) do |suite_config|
    suite_config.world_modules << DriveDomain
    suite_config.filters << TagFilter.new("~@web")
    suite_config.filters << LocationFilter.new("features/core")
  end

  config.suite(:web) do |suite_config|
    suite_config.world_modules << DriveUI
    suite_config.filters << TagFilter.new("@web")
  end
end
```
Does that get written somewhere in the support directory like `env.rb`?

**Comment by mattwynne** [comment]
You could actually use an `AfterConfiguration` block for now, and yes, call it from `env.rb`

**Comment by richarda** [comment]
Still working ... Update soon.

**Comment by mattwynne** [comment]
Closing due to inactivity. This was a tough one to tackle @richarda. Feel free to ping us if you'd like to get involved again with something easier!

**Pull request closed without merging**
