### PR TITLE
Refs #1021 - Fixes the rubocop violation 'Style/StringLiterals'

### LINKED ISSUE #1021: Fix style violations
At the moment, the codebase has several style violations. It would be great to refactor the code, such that we are up to date with the community best practices https://github.com/bbatsov/ruby-style-guide.

The list of the violations is in two files:
- https://github.com/cucumber/cucumber-ruby/blob/master/.rubocop_todo.yml (auto generated)
- https://github.com/cucumber/cucumber-ruby/blob/master/.rubocop.yml

These files specify the ignored violations. It would be great to remove some of the violations from the files and fix them progressively in order to keep the PRs small.

### PR DESCRIPTION
**Pull request by pmatsinopoulos**
## Summary

Fixed the `Style/StringLiteral` [rubocop](https://github.com/bbatsov/rubocop) offending code.

## Motivation and Context

This change fix part of #1021. It does not fix it completely, but only partially. Other PRs will follow on same issue.

## How Has This Been Tested?

No new tests have been added. But existing tests run green. Also [rubocop](https://github.com/bbatsov/rubocop) is happy with the `Style/StringLiterals` enabled.

## Screenshots (if appropriate):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Style changes to make [rubocop](https://github.com/bbatsov/rubocop) happy.

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mattwynne** [comment]
@cucumber/cucumber-ruby would any of you like to help merge these in? You all have the appropriate permissions!

**Comment by mattwynne** [comment]
Thanks a lot @pmatsinopoulos - keep them coming, we appreciate it!

**Comment by brasmusson** [comment]
@pmatsinopoulos You need to careful when you write the PR description, you used `"fix #1021"`, that is a [wording](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) that will trigger Github to automatically close the referred issue when the RP is merged. I changed it to `"fix part of #1021"` to inhibit Github to do that.

**Comment by pmatsinopoulos** [comment]
@brasmusson 
> @pmatsinopoulos You need to careful when you write the PR description

Ooooh! Didn't know that. Sorry. Thanks for letting me know! Will definitely make sure will not happen again.

**Comment by mattwynne** [comment]
any chance you could rebase this @pmatsinopoulos?

**Comment by pmatsinopoulos** [comment]
> any chance you could rebase this @pmatsinopoulos?

@mattwynne gladly will do that. But will be tomorrow. I am travelling today.

**Comment by pmatsinopoulos** [comment]
@mattwynne I finally did that a while ago. Conflicts with master have been resolved.

**Comment by nodo** [comment]
Hi @pmatsinopoulos, I am sorry I have been merging some other PRs about style and now your PR has conflicts again. Please, could you resolve the conflicts and rebase? As soon as you do it I will get it merged.

Thanks a lot for your work, really appreciated.

**Comment by pmatsinopoulos** [comment]
@nodo Ready. No problem!

**Comment by nodo** [comment]
Thanks a lot @pmatsinopoulos ! Looks good 👍

**Pull request merged**
