### PR TITLE
Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

> Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

https://www.legitsecurity.com/blog/github-privilege-escalation-vulnerability

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Heya, thanks for all the links. I think I understand what you are trying to convey but I don't understand why you've only changed one file.

Are you looking to contribute or is this a bug report with example fix?

**Comment by naveensrinivasan** [comment]
> Heya, thanks for all the links. I think I understand what you are trying to convey but I don't understand why you've only changed one file.
> 
> Are you looking to contribute or is this a bug report with example fix?

This is a fix for just one file, which I was able to do. You can consider this as an example fix.

**Comment by aurelien-reeves** [comment]
Thanks @naveensrinivasan to point that permissions thing to us.

As we have a lot of repositories and more workflows in the cucumber organization, I guess we may consider configuring that at the organization level, and set more permissive permissions when this would be required. Do you think that would be a good thing? @mpkorstanje @mattwynne @aslakhellesoy what would be your opinion on that?

**Comment by naveensrinivasan** [comment]
That is a good idea. But how do you override those permissions? That has to be done in the code. 

Also keeping this in the code will guarantee that even if those org permissions are changed this will be a fallback. 

This will also have a way of auditing changes. 

I'll let you decide. 👍

**Comment by aurelien-reeves** [comment]
I close that one as we actually need to do such things at a higher level.

Still, thanks for pointing that out to us

**Pull request closed without merging**
