### PR TITLE
remove reference to protobuf in formatters help

### PR DESCRIPTION
**Pull request by davidjgoss**

### CODE REVIEW

**Comment by olleolleolle** [comment]
This is a helpful change, and the message is now more truthful.

**Review by olleolleolle — APPROVED** [review]
Looks good to me, please merge the change!

**Review by luke-hill — APPROVED** [review]
I had to check the logs to check we have actually got rid of them. Although it's not actually out cut as a version yet I don't believe.

**Comment by aslakhellesoy** [comment]
The `main` branch still uses protobuf messages since #1554 isn't merged yet, but this change is still valid.

**Pull request merged**
