### PR TITLE
Refactoring for Rakefile to display cucumber task by "rake -T".

### PR DESCRIPTION
**Pull request by junaruga**
## Summary

I want to display cucumber task by "rake -T".
It is not displayed because the cucumber task does not have a description.
This is a refactoring for `Rakefile`.

## Details

Current situation

Display tasks with description.
`cucumber` task is not displayed.

```
$ bundle exec rake -T
rake build                 # Build cucumber-3.0.0.pre.1.gem into the pkg directory
rake clean                 # Remove any temporary products
rake clobber               # Remove any generated files
rake contributors          # List contributors
rake cov                   # Run all tests and collect code coverage
rake examples              # Run all exmples
rake features              # Run Cucumber features
rake fix_cr_lf             # Make all files use UNIX (\n) line endings
rake flog                  # Run flog over significant files
rake install               # Build and install cucumber-3.0.0.pre.1.gem into syst...
rake install:local         # Build and install cucumber-3.0.0.pre.1.gem into syst...
rake release[remote]       # Create tag v3.0.0.pre.1 and build and push cucumber-...
rake rubocop               # Run RuboCop
rake rubocop:auto_correct  # Auto-correct RuboCop offenses
rake sass                  # Generate the css for the html formatter from sass
rake spec                  # Run RSpec
```

Display all the tasks including tasks without description.
`cucumber` task is displayed.

```
$ bundle exec rake -AT
rake build                                # Build cucumber-3.0.0.pre.1.gem into t...
rake clean                                # Remove any temporary products
rake clobber                              # Remove any generated files
rake codeswarm                            #-
rake contributors                         # List contributors
rake cov                                  # Run all tests and collect code coverage
rake cucumber                             #-
rake default                              #-
rake examples                             # Run all exmples
rake features                             # Run Cucumber features
rake fix_cr_lf                            # Make all files use UNIX (\n) line end...
rake flog                                 # Run flog over significant files
rake install                              # Build and install cucumber-3.0.0.pre....
rake install:local                        # Build and install cucumber-3.0.0.pre....
rake release[remote]                      # Create tag v3.0.0.pre.1 and build and...
rake release:guard_clean                  #-
rake release:rubygem_push                 #-
rake release:source_control_push[remote]  #-
rake rubocop                              # Run RuboCop
rake rubocop:auto_correct                 # Auto-correct RuboCop offenses
rake ruby_env                             #-
rake sass                                 # Generate the css for the html formatt...
rake spec                                 # Run RSpec
```

After modification
`cucumber` task is displayed by "rake -T".

```
$ bundle exec rake -T
rake build                 # Build cucumber-3.0.0.pre.1.gem into the pkg directory
rake clean                 # Remove any temporary products
rake clobber               # Remove any generated files
rake contributors          # List contributors
rake cov                   # Run all tests and collect code coverage
rake cucumber              # Run Cucumber features
rake examples              # Run all exmples
rake features              # Run Cucumber features
rake fix_cr_lf             # Make all files use UNIX (\n) line endings
rake flog                  # Run flog over significant files
rake install               # Build and install cucumber-3.0.0.pre.1.gem into syst...
rake install:local         # Build and install cucumber-3.0.0.pre.1.gem into syst...
rake release[remote]       # Create tag v3.0.0.pre.1 and build and push cucumber-...
rake rubocop               # Run RuboCop
rake rubocop:auto_correct  # Auto-correct RuboCop offenses
rake sass                  # Generate the css for the html formatter from sass
rake spec                  # Run RSpec
```

## Motivation and Context

I want to see `cucumber` task by "rake -T".

Also below codes can be improved to simplify it.

```
task :default => [:spec, :rubocop, :cucumber]
...
task :default => [:spec, :rubocop, :cucumber, 'coveralls:push']
```

## How Has This Been Tested?

I tested my code running `rake -T` and `rake -AT`.
Travis tests it too.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mattwynne** [comment]
There's a file in `gem_tasks/cucumber.rake` that this change is effectively making redundant.

One of the things that file does is set the correct profile for the platform. We're deprecating (or have removed) some of those platforms as you know, but not all of them.

Also that file sets the `fork` option on the rake task. I'm not sure what that does without looking it up, but it's worth some investigation.

In general I'd be delighted if we could remove that file and replace it with this, which looks much simpler. It might be that we need to carry over a little bit more though, for example to make sure the build works on a Windows machine.

**Comment by junaruga** [comment]
@mattwynne ok I understood current situation. Let me check the source code more.

**Comment by junaruga** [comment]
@mattwynne 
I agree with you about it is redundant. I did not  check `gem_tasks/cucumber.rake`.

- `fork`: it's default value is `true`. So, technically I think that we do not need to set `fork = true` in the `gem_tasks/cucumber.rake`. 
  Reading the comment of this, `fork = true` may be needed to run with Bundler.
  https://github.com/cucumber/cucumber-ruby/blob/master/lib/cucumber/rake/task.rb#L114-L117

- there is `profile` setting in `gem_tasks/cucumber.rake`. 
  I updated `cucumber.yml` too for that.
  But I wonder that the profiles `ruby_x_y` is really needed for each Ruby version.
  How do you think?

- I added `desc` in `gem_tasks/cucumber.rake` right now.
  This looks better right now to display cucumber task with `rake -T` .

I did rebase my code on this PR.

**Comment by mattwynne** [comment]
I think you're right that the ruby version profiles are mostly redundant now. They're certainly messy, so if we can remove them I think we should.

I also liked the way you'd simplified this in the original PR. If you were to remove `gem_tasks/cucumber.rake` I'd be happy, as long as nothing seriously broke.

This is only stuff for us devs to use anyway, so it's worth taking some risks if it helps us to clean things up.

**Comment by junaruga** [comment]
I pushed additional commit after your comment.
How do you think?

Seeing this commit 8d6deddf3cec0f89b0e54c5bc7867c086fe9611b ,
`Cucumber::JRUBY, WINDOWS, OS_X, WINDOWS_MRI` are outdated.
Do you want to remove the those settings in `cucumber.yml` and logics where those variables are used under lib/ too?
Do you want to keep profile setting in `Railefile` cucumber task? or can I remove the profile setting logic too?

**Comment by junaruga** [comment]
If there is not any opposition, I am going to merge this PR after tomorrow.

**Comment by mattwynne** [comment]
👍

**Comment by mattwynne** [comment]
@junaruga please add a line in HISTORY.md after you merge.

**Pull request merged**
